# ui_components/module_3_forecaster.py
import streamlit as st
import pandas as pd
import plotly.express as px
import requests
import json
from datetime import date, timedelta
from textwrap import dedent

# Import both definitions and keywords from our constants file
from constants import CATEGORY_DEFINITIONS, CATEGORY_KEYWORDS

# ==============================================================================
# Helper Function to Fetch News (Moved into this file)
# ==============================================================================
def fetch_latest_news(days_to_fetch=30):
    """
    Fetches the last N days of news from the AIID GraphQL API.
    It uses chunking for reliability and retries for resilience.
    """
    print(f"--- FETCHING LATEST NEWS for the last {days_to_fetch} days ---")
    
    url = "https://incidentdatabase.ai/api/graphql"
    headers = {'Content-Type': 'application/json'}

    end_date = date.today()
    start_date = end_date - timedelta(days=days_to_fetch)
    
    list_of_date_strings = []
    current_date = start_date
    while current_date <= end_date:
        list_of_date_strings.append(current_date.strftime('%Y-%m-%d'))
        current_date += timedelta(days=1)
    
    # =========================================================================
    # ### START OF THE FIX: Re-introducing Chunking with Retries ###
    # =========================================================================

    chunk_size = 15 # Use smaller chunks to be safer (e.g., ~2 weeks)
    all_candidates = []
    retries = 2

    print(f"Splitting request into chunks of {chunk_size} days.")
    for i in range(0, len(list_of_date_strings), chunk_size):
        chunk_dates = list_of_date_strings[i:i + chunk_size]
        
        payload = {
            "operationName": "NewsArticles",
            "variables": {"filter": {"match": {"EQ": True}, "date_published": {"IN": chunk_dates}}},
            "query": "query NewsArticles($filter: CandidateFilterType!) {\n  candidates(filter: $filter) {\n    title\n    url\n    date_published\n    text\n    similarity\n    matching_harm_keywords\n  }\n}"
        }

        # --- Retry loop for each chunk ---
        for attempt in range(retries):
            try:
                response = requests.post(url, headers=headers, data=json.dumps(payload), timeout=30)
                if response.status_code == 200:
                    response_data = response.json()
                    candidates = response_data.get('data', {}).get('candidates', [])
                    print(f"-> Chunk {i // chunk_size + 1}: Success, found {len(candidates)} articles.")
                    all_candidates.extend(candidates)
                    break # Success, so break the retry loop and move to the next chunk
                else:
                    print(f"-> Chunk {i // chunk_size + 1}, Attempt {attempt + 1}: API returned status {response.status_code}")
            
            except requests.exceptions.RequestException as e:
                print(f"-> Chunk {i // chunk_size + 1}, Attempt {attempt + 1}: Network error: {e}")
            
            if attempt < retries - 1:
                print("-> Retrying chunk...")

    print(f"--- TOTAL FOUND across all chunks: {len(all_candidates)} ---")
    return all_candidates


def display_dynamic_forecaster(data):
    """Displays Module 3, now with the integrated 'On the Radar' feature."""
    st.header("Module 3: The Dynamic Forecaster")
    st.markdown("This module provides a 3-year forecast for any selected harm category. Categories are sorted by their recent growth trend, with the top 'hotspot' selected by default.")

    with st.expander("🔬 View Forecasting Methodology"):
        st.markdown(dedent("""
        The forecast is generated by fitting a **Simple Linear Regression** model to the historical data. The model is fitted **only on the most recent three years (12 quarters)** of complete historical data to be responsive to the latest trends.
        """))

    all_forecasts_data = data['all_forecasts_data']
    sorted_categories = [item['category_name'] for item in all_forecasts_data]
    
    selected_category = st.selectbox('Select a harm category to forecast:', options=sorted_categories)

    if selected_category:
        # --- Display the Forecast Chart (existing logic) ---
        selected_data_object = next((item for item in all_forecasts_data if item['category_name'] == selected_category), None)
        if selected_data_object:
            df_forecast = pd.DataFrame(selected_data_object['data'])
            st.subheader(f"Incident Trajectory for: **{selected_category}**")
            definition = CATEGORY_DEFINITIONS.get(selected_category, "No definition available.")
            st.info(f"**Definition:** {definition}")
            # ... (plotting code remains the same) ...
            fig_forecast = px.line(
                df_forecast, x='quarter_str', y='incident_count', color='type', line_dash='type', markers=True,
                labels={'quarter_str': 'Quarter', 'incident_count': 'Number of Incidents', 'type': 'Data Type'}, height=500,
                color_discrete_map={'Historical': 'royalblue', 'Forecast': 'darkorange'},
                line_dash_map={'Historical': 'solid', 'Forecast': 'dash'}
            )
            fig_forecast.update_traces(line=dict(width=3))
            st.plotly_chart(fig_forecast, use_container_width=True)
            
        # =========================================================================
        # ### START OF NEW INTEGRATED "ON THE RADAR" CODE ###
        # =========================================================================
        with st.expander(f"📡 On the Radar: See Latest Events for '{selected_category}'"):
            with st.spinner("Fetching and analyzing the latest news..."):
                articles = fetch_latest_news()

                if not articles:
                    st.warning("Could not fetch the latest news at this time. Please try again later.")
                else:
                    df_articles = pd.DataFrame(articles)
                    keywords = CATEGORY_KEYWORDS.get(selected_category, [])

                    if not keywords:
                        st.info("No specific keywords are defined for this category to filter news.")
                    else:
                        def calculate_relevance(row):
                            score = 0
                            text_to_search = f"{row.get('title', '')} {row.get('text', '')}".lower()
                            for keyword in keywords:
                                if keyword in text_to_search:
                                    score += 1
                            if isinstance(row.get('matching_harm_keywords'), list):
                                for harm_keyword in row['matching_harm_keywords']:
                                    if harm_keyword in keywords:
                                        score += 2
                            return score

                        df_articles['relevance_score'] = df_articles.apply(calculate_relevance, axis=1)
                        df_relevant = df_articles[df_articles['relevance_score'] > 0].sort_values(by=['relevance_score', 'similarity'], ascending=False)

                        if df_relevant.empty:
                            st.info(f"No recent news articles matching the keywords for **{selected_category}** were found in the last 30 days.")
                        else:
                            st.success(f"Found {len(df_relevant)} relevant articles. Displaying the Top 9.")
                            
                            # --- Create a 3-column layout ---
                            cols = st.columns(3)
                            
                            # Get the top 9 articles
                            top_articles = df_relevant.head(9)

                            for index, row in top_articles.iterrows():
                                # Use modulo operator to cycle through columns 0, 1, 2
                                target_col = cols[index % 3]
                                
                                with target_col:
                                    # --- Format date ---
                                    date_obj = pd.to_datetime(row['date_published'])
                                    formatted_date = date_obj.strftime('%d-%m-%Y') # DD-MM-YYYY
                                    
                                    # --- Format harm tags as HTML spans ---
                                    tags_html = ""
                                    if isinstance(row.get('matching_harm_keywords'), list) and row['matching_harm_keywords']:
                                        tags_html = "".join([f"<span class='tag'>{tag}</span>" for tag in row['matching_harm_keywords']])
                                    
                                    # --- Build the HTML for the card ---
                                    card_html = f"""
                                        <div class="news-card">
                                            <a href="{row['url']}" target="_blank">{row['title']}</a>
                                            <p style="font-size: 0.9em; color: grey; margin-top: 10px;">Published: {formatted_date}</p>
                                            <div class="tags">{tags_html}</div>
                                        </div>
                                    """
                                    st.markdown(card_html, unsafe_allow_html=True)
                            
                            st.markdown("---")
                            st.info("News sourced from the AI Incident Database News Digest. **[Click here to view the full, live feed.](https://incidentdatabase.ai/apps/newsdigest/)**")
        # ### END OF NEW CODE ###
        # =========================================================================

    else:
        st.warning("Please select a category to view its forecast.")

    return selected_category