import streamlit as st
import pandas as pd
import plotly.express as px

from textwrap import dedent

# Import both definitions and keywords from our constants file
from constants import CATEGORY_DEFINITIONS, CATEGORY_KEYWORDS

def display_dynamic_forecaster(data):
    """Displays Module 3, now with the integrated 'On the Radar' feature."""
    st.header("Module 3: The Dynamic Forecaster")
    st.markdown("This module provides a 3-year forecast for any selected harm category. Categories are sorted by their recent growth trend, with the top 'hotspot' selected by default.")

    with st.expander("🔬 View Forecasting Methodology"):
        st.markdown(dedent("""
        The forecast is generated by fitting a **Simple Linear Regression** model to the historical data. The model is fitted **only on the most recent three years (12 quarters)** of complete historical data to be responsive to the latest trends.
        """))

    all_forecasts_data = data['all_forecasts_data']
    sorted_categories = [item['category_name'] for item in all_forecasts_data]
    
    selected_category = st.selectbox('Select a harm category to forecast:', options=sorted_categories)

    if selected_category:
        # --- Display the Forecast Chart (existing logic) ---
        selected_data_object = next((item for item in all_forecasts_data if item['category_name'] == selected_category), None)
        if selected_data_object:
            df_forecast = pd.DataFrame(selected_data_object['data'])
            st.subheader(f"Incident Trajectory for: **{selected_category}**")
            definition = CATEGORY_DEFINITIONS.get(selected_category, "No definition available.")
            st.info(f"**Definition:** {definition}")
            fig_forecast = px.line(
                df_forecast, x='quarter_str', y='incident_count', color='type', line_dash='type', markers=True,
                labels={'quarter_str': 'Quarter', 'incident_count': 'Number of Incidents', 'type': 'Data Type'}, height=500,
                color_discrete_map={'Historical': 'royalblue', 'Forecast': 'darkorange'},
                line_dash_map={'Historical': 'solid', 'Forecast': 'dash'}
            )
            fig_forecast.update_traces(line=dict(width=3))
            st.plotly_chart(fig_forecast, use_container_width=True)
            
    else:
        st.warning("Please select a category to view its forecast.")

    return selected_category